# Generated by Django 4.0.5 on 2023-01-03 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=900)),
                ('date', models.DateField(default=datetime.date(2023, 1, 3))),
                ('importance', models.BooleanField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
