# Generated by Django 4.0.5 on 2023-01-07 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='urgencyTimeRange',
            field=models.DurationField(default=datetime.timedelta(days=3)),
        ),
    ]
